### ISSUE TITLE
Saccade Detector icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#13]
Saccades are fast, sudden eye movements. The icon could feature an eye and motion lines

**Comment by willpatera** [comment]
@papr does this plugin exist?

**Comment by papr** [comment]
Not yet, but I have an idea for an easy implementation. Should not take longer than an hour. It will work similar to the fixation plug in.

**Comment by nathakits** [comment]
@papr @willpatera - something like this?
![saccade](https://user-images.githubusercontent.com/17331040/31248839-5a5ece78-aa3f-11e7-8f09-a4f8ae0d46c5.PNG)

**Comment by papr** [comment]
Maybe fill the Pupil instead of the right side of the eye ball? But I like it already

**Comment by nathakits** [comment]
@papr - i don't quite understand what you are saying. Can you explain it again?

**Comment by papr** [comment]
The more or less elliptical outline represents the eye lids, therefore the background of its content is the eye ball itself and is usually white. The pupil is usually black and moves together with the iris, represented by the white circle in this picture.

The speed line end at the iris which is good. My suggestion was to keep the eye lids, remove the right black part of the eye ball, make it transparent as well, and fill the Pupil with black.

**Comment by nathakits** [comment]
@papr I think in the case of Material `eye` icon, the thick black outline represents both the eyelid and the eye ball, with the white circle as the iris and the black ball as the pupil. IMO makes the icon stand out with good contrast between the elements in the icon. After all the icon should be simplified and an abstract representation of what it is trying to show.

My icon above from the previous mock-up just took the Material `eye` icon and added the lines in to represent the movement of the eye and still keep the original identity of the icon. 

I see most of what you are saying now except for the part where making the Pupil is black, so i made 3 examples from what i can understand your comments. But i think by making it eyeball all white would make the icon lose the representation of `speed` due to the lack of contrast of the `eye` icon.

![accuracy_vis_example](https://user-images.githubusercontent.com/17331040/31270290-f98b7442-aaad-11e7-8122-bf3595f764a6.png)

To conclude, i think the icon above from the previous comment i posted represents the `saccade` better but if the team doesn't think it's good enough we can certainly take this to another direction,

**Comment by mkassner** [comment]
I actually think this one is very good:

![screen shot 2017-10-06 at 11 07 55](https://user-images.githubusercontent.com/1433767/31270959-a5184f2e-aa86-11e7-8f56-170fae14fc55.png)


I like this partially white and partially back pupil. 

Lets keep Nats first design!

**Comment by papr** [comment]
As it turns out the contrast between left (speed lines) and right side (filled eye ball) is not enough. We might need a revision in the future.
